#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH -N 1
#SBATCH -C cpu
#SBATCH -q debug
#SBATCH -J test
#SBATCH -t 0:30:00
#SBATCH -o test.out

# OpenMP settings:
export OMP_NUM_THREADS=32
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

#run the application: 
srun -n 1 -c 256 --cpu_bind=cores  target/release/deps/spec_spars-763c6ce7107d8910
