#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH -N 1
#SBATCH -C cpu
#SBATCH -q regular
#SBATCH -J test
#SBATCH -t 5:00:00
#SBATCH -o test.out

# OpenMP settings:
export OMP_NUM_THREADS=32
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

#run the application: 
#srun -n 1 -c 256 --cpu_bind=cores  valgrind --tool=massif target/release/deps/spec_spars-97c4c6c3b9ee420b file_only_solver_test
srun -n 1 -c 256 --cpu_bind=cores  target/release/deps/pec_spars-4473b84cdf66a593
