#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH -N 1
#SBATCH -C cpu
#SBATCH -q regular
#SBATCH -J txt_to_mtx
#SBATCH -t 10:00:0
#SBATCH -o txt_to_mtx.out

# OpenMP settings:
export OMP_NUM_THREADS=32
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

#run the application: 
module load julia
julia reference_implementation/txt_to_mtx.jl
